### PR TITLE
Update docs for ODM - updating Storage Classes to show managed-nfs-storage is a viable option 

### PR DESCRIPTION
**Pull request by vbudi000**
Should the default be changed to managed-nfs-storage for ODM? - @therayy ?

### CODE REVIEW

**Comment by therayy** [comment]
I think if its working why not :D

**Comment by therayy** [comment]
merge this please

**Review by therayy — COMMENTED** [review]
this is not correct
the DB2 operator is ibm-cp4ba-db2
the instance is ibm-cp4ba-db2ucluster so please remove line 62 and keep line 61 as is

**Review by hollisc — APPROVED** [review]
Looks good

**Pull request merged**
