### PR TITLE
SFG recipe

### PR DESCRIPTION
**Pull request by therayy**
- [x] URL directs you to what is SFG ibm url
- [X] adding all warnings and notes to push and sync argo
- [x] updating the section after deployment before validation with a warning in case of you decided to scale the pods or upgrade the version you should do the following steps
- [X] Reason why we are disabling the `datasetup` & `dbcreateschema`

**_* WE NEED TO ADD THE PVC YAMLS & FIX THE CHART VERSION TO 2.0.4 *_**

### CODE REVIEW

**Comment by therayy** [comment]
@hollisc  please take a look.

**Review by therayy — COMMENTED** [review]
adding a proper icon to notes

**Review by therayy — COMMENTED** [review]
trying out to fix the dco

**Review by therayy — COMMENTED** [review]
Signed-off-by: Ray Abaid Raafat@ibm.com

**Review by therayy — COMMENTED** [review]
done

**Review by hollisc — APPROVED** [review]
LGTM

**Pull request merged**
