### PR TITLE
updating ibm ace operator to v4.2

### PR DESCRIPTION
**Pull request by mlasprilla**
Updating ibm ace operator channel from v1.5 to v4.2. Channel v4.2 supports OpenShift 4.6, 4.7, 4.8, 4.10. Most recent status is v7.1 that only supports 4.10.

### CODE REVIEW

**Comment by davidstacy** [comment]
hmm I just merged the previous commit that updates it to 7.2, is that better than this -but you are also catching in more places.


here is the docs:
https://www.ibm.com/docs/en/app-connect/containers_cd?topic=operator-from-openshift-cli

**Comment by davidstacy** [comment]
@hollisc  can you merge?  showing grayed out for me.

**Comment by hollisc** [comment]
> @hollisc can you merge? showing grayed out for me.

Hey @davidstacy, there is a merge conflict.  @mlasprilla, can you please update the PR to fix the conflict.  Thanks!

**Comment by davidstacy** [comment]
will do @mlasprilla if this note tags you can you fix the conflict and we will approve the PR...

**Pull request merged**
