### PR TITLE
Add grafana-instana to services

### PR DESCRIPTION
**Pull request by lsteck**
We need to add the grafana-instana reference to the `multi-tenancy-gitops-services` repo

### CODE REVIEW

**Comment by hollisc** [comment]
@lsteck, can you sync the the changes from the single-cluster profile to the multi-cluster profiles.  You can run /scripts/sync-manifests.sh to do this.

**Review by hollisc — COMMENTED** [review]
Can you sync the changes from the single-cluster profile to the multi-cluster profiles.

**Comment by lsteck** [comment]
@hollisc Done.  I didn't know about that script.  Awesome!

**Comment by lsteck** [comment]
@hollisc I also added the move of the service-account out of the robot-shop in the helm values

**Review by hollisc — APPROVED** [review]
LGTM

**Pull request merged**
