### PR TITLE
merged bootstrap - adding popd to tls

### PR DESCRIPTION
**Pull request by vbudi000**
Signed-off-by: Budi Darmawan <vbudi@us.ibm.com>

- I merged but not deleted the bootstrap-gitea.sh (if everything is ok - I can add the deletion of bootstrap-gitea,sh to the pr)
- I added a popd before return from the gitops tls cert

### CODE REVIEW

**Review by lsteck — CHANGES_REQUESTED** [review]
@vbudi000 

Can you change the GIT_ORG check on line 30 `if [[ -z ${GIT_ORG} ]]; then` to not check if `USE_GITEA="true"`  and add back in the "default" `GIT_ORG=${GIT_ORG:-gitops-org}`

I think something like a if/else if:

```
if USE_GITEA = true
    GIT_ORG=${GIT_ORG:-gitops-org}
else  if [[ -z ${GIT_ORG} ]]; then
  .....
```

**Comment by vbudi000** [comment]
Sure - forgot bout that - was thinking of adding that before ....

**Review by hollisc — APPROVED** [review]
Looks good

**Review by lsteck — CHANGES_REQUESTED** [review]
Hi @vbudi000 

I think we need one last change.  Can you change the `set_git_source ()` to the following?  I'm testing this now. 
```
set_git_source () {
  echo setting git source instead of git override
  pushd ${OUTPUT_DIR}/gitops-0-bootstrap

  if [[ "${GITOPS_PROFILE}" == "0-bootstrap/single-cluster" ]]; then
    rm -r 0-bootstrap/others
  fi

  if [[ "${USE_GITEA}" == "true" ]]; then
    GIT_ORG=${GIT_ORG} \
    GIT_BASEURL=${GITEA_PROTOCOL}://${GITEA_HOST} \
    GIT_GITOPS_BRANCH=${GITEA_GITOPS_BRANCH} \
    GIT_GITOPS_INFRA_BRANCH=${GITEA_GITOPS_INFRA_BRANCH} \
    GIT_GITOPS_SERVICES_BRANCH=${GITEA_GITOPS_SERVICES_BRANCH} \
    GIT_GITOPS_APPLICATIONS_BRANCH=${GITEA_GITOPS_APPLICATIONS_BRANCH} \
    ./scripts/set-git-source.sh

    git remote add origin ${GITEA_BASEURL}/${GIT_ORG}/${GIT_GITOPS}
    git push --set-upstream origin ${GITEA_GITOPS_BRANCH}
  else
    GIT_ORG=${GIT_ORG} ./scripts/set-git-source.sh
    if [[ ${GIT_TOKEN} ]]; then
      git remote set-url origin ${GIT_PROTOCOL}://${GIT_TOKEN}@${GIT_HOST}/${GIT_ORG}/${GIT_GITOPS}
    fi
  fi

  git add .
  git commit -m "Updating git source to ${GIT_ORG}"
  git push origin
  popd
}
```

**Comment by hollisc** [comment]
@lsteck, can you review and merge.  Thanks!

**Comment by vbudi000** [comment]
Will split the pull request into 2 - will be redoing this

**Pull request closed without merging**
