### PR TITLE
Added updated SSP recipe, cleaned up hook generation

### PR DESCRIPTION
**Pull request by Knickkennedy**
Signed-off-by: Knicholas Kennedy <Knicholas.Kennedy@ibm.com>

This is a pretty comprehensive cleanup and rework of the gitops configuration for the SSP containerized deployment.

### CODE REVIEW

**Comment by hollisc** [comment]
Please add a md file for the SSP recipe as well in the docs folder.

**Comment by Knickkennedy** [comment]
> Please add a md file for the SSP recipe as well in the docs folder.

Fixed

**Comment by hollisc** [comment]
@Knickkennedy, in the recipe md file, can we provide the oc cmd for the user to retrieve the SSP URL and list the default credentials from the env file.  Otherwise it looks good.

**Comment by Knickkennedy** [comment]
@hollisc added default credentials and route command!

**Review by hollisc — APPROVED** [review]
Looks good

**Comment by hollisc** [comment]
This PR depends on merge of https://github.com/cloud-native-toolkit/multi-tenancy-gitops-services/pull/61

**Comment by vbudi000** [comment]
Just some comments on the documentation - maybe @Knickkennedy can put those in before the merge:
- the RWO is a PVC access mode - not a memory (step 1 under Services customization)
- formatting error on the line with `ibmc-file-silver` - also using ibmc-file 
allows RWX - not solely RWO - `ibmc-block-*` may be better as an example
-I suggest creating a template "ssp-env.sh" (or "ssp-env.sh.template" in the same path as "run-setup.sh" so that the passwords can then be modified. would be a lot easier for the user - or better yet - put the template on the top of run-setup.sh 
- the run-setup.sh does NOT creates the PVC and Secrets - it creates the YAML constructs for the PVC and Secrets

**Comment by vbudi000** [comment]
Your run-setup.sh has an error that the kubeseal output is going to the terminal instead of a YAML file

**Comment by vbudi000** [comment]
Another - the list in SCC volumes should be alphabetical - otherwise it will show as OOS

**Comment by vbudi000** [comment]
Several more:
- May need to provide password requirement for SSP passphrase
- Services must be "ClusterIP" instead of "LoadBalancer" otherwise it wont sync 
- Got error running the hook job - rsync is unavailable
```
pod/ibm-ssp-cm-ibm-ssp-cm-0 condition met
Defaulted container "ibm-ssp-cm-ibm-ssp-cm" out of: ibm-ssp-cm-ibm-ssp-cm, ibm-ssp-cm-ibm-ssp-cm-init-secret (init)
WARNING: cannot use rsync: rsync not available in container
Defaulted container "ibm-ssp-cm-ibm-ssp-cm" out of: ibm-ssp-cm-ibm-ssp-cm, ibm-ssp-cm-ibm-ssp-cm-init-secret (init)
tar: defkeyCert.txt: Cannot stat: Permission denied
tar: Exiting with failure status due to previous errors
error: error creating remote tar of source directory: command terminated with exit code 2
error: error reading ./tmp/defkeyCert.txt: no such file or directory
error: no objects passed to apply
```

**Comment by vbudi000** [comment]
All pods are running, but the last verification steps to connect to CM cant get through; the cm sts logs has this:
```
Exception in thread "qtp432306461-24" java/lang/NoClassDefFoundError: com.ibm.oti.util.Msg
at java/lang/ThreadGroup.uncaughtException (ThreadGroup.java:867)
at java/lang/ThreadGroup.uncaughtException (ThreadGroup.java:861)
at java/lang/Thread.uncaughtException (Thread.java:1336)
```

**Comment by vbudi000** [comment]
Summary:
- Some suggestions on the docs (PVC RWO/RWX, mod the env variables, password rule, f/up with the updates below) 
- Modification of run-setup.sh https://github.com/vbudi-gitops-test/multi-tenancy-gitops-services/blob/master/instances/sterling-secure-proxy-setup/run-setup.sh
- Modification of the hook job: https://github.com/vbudi-gitops-test/multi-tenancy-gitops-services/blob/master/instances/sterling-secure-proxy-hook/keycert-hook-job.yaml

**Comment by davidstacy** [comment]
can this be merged?  anyone test recently?  @hollisc @vbudi000

**Comment by davidstacy** [comment]
can this be merged?  anyone test recently?  @hollisc @vbudi000

**Comment by hollisc** [comment]
> can this be merged? anyone test recently? @hollisc @vbudi000

@Knickkennedy , can you please have a look at Budi's comments above, I believe we were waiting for those changes to get into the PR before merging.

**Comment by davidstacy** [comment]
@Knickkennedy @hollisc following up - can this be merged?

**Pull request closed without merging**
