### PR TITLE
Added sccm resources

### PR DESCRIPTION
**Pull request by jsaez-ibm**
Added resources for deploying Sterling Control Center Monitor (SCCM)

### CODE REVIEW

**Comment by vbudi000** [comment]
There are several things:
- your commit is not signed
- there is a duplicate file 1-infra.yaml on the wrong folder 
- can you please add a link to the linked PR for the multi-tenancy-gitops-infra and multi-tenancy-gitops-services in the PR 
- In ibm-sccm.yaml - you can remove the helm.values commented section if you are using the values.yaml script

**Comment by jsaez-ibm** [comment]
Related PR's:
https://github.com/cloud-native-toolkit/multi-tenancy-gitops-infra/pull/37
https://github.com/cloud-native-toolkit/multi-tenancy-gitops-services/pull/51

**Comment by hollisc** [comment]
Also, can you run /scripts/sync-manifests.sh as this will copy the SCCM resources to the multi-cluster profiles as well.

**Comment by jsaez-ibm** [comment]
@hollisc where did you want me to run sync-manifests.sh?

**Comment by hollisc** [comment]
> 

@jsaez-ibm, the `sync-manifests.sh` is in the /script folder.

**Comment by hollisc** [comment]
@vbudi000 and I had a review with @jsaez-ibm.  Waiting on an update and final test before merging.

**Comment by jsaez-ibm** [comment]
Converted to draft for now - while still merging and testing with the latest versions of SCCM container image and helm chart

**Review by hollisc — APPROVED** [review]
Looks good

**Pull request merged**
