### PR TITLE
Apic multicloud use case

### PR DESCRIPTION
**Pull request by jesusmah**

### CODE REVIEW

**Review by hollisc — APPROVED** [review]
Reviewed with Jesus, looks good

**Comment by vbudi000** [comment]
SPP resources were removed from 2-services/kustomization.yaml

**Comment by vbudi000** [comment]
@hollisc - should I create a new PR?

**Comment by jesusmah** [comment]
Hey @vbudi000 yeah, just realised about it. Sorry about that. And as far as I am concerned, I think the best would be if you create a new PR adding those changed to `2-services/kustomization.yaml`. It should pretty fast to review and accept.

**Pull request merged**
